version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/node:8.11.3-browsers
    environment:
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8
          MOCHA_FILE: $CIRCLE_TEST_REPORTS/junit/test-results.xml
    steps:
      - checkout
      - run: 
          name: Update Yarn
          command: 'sudo npm update -g yarn'
      - restore-cache:
          name: Restore Yarn Package Cache
          keys: 
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save-cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: 
          name: Build
          command: yarn run build
      - run: 
          name: Lint
          command: yarn run lint
      - run: 
          name: Run Tests
          command: yarn run ci:test
      - store_artifacts:
          path: $CIRCLE_TEST_REPORTS/junit/test-results.xml
      - store_artifacts:
          path: dist

workflows:
  version: 2
  build-test-report:
    jobs:
      - build-and-test